---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: "Remove unofficial docker images"
  package:
    name: 
      - docker.io
      - docker-compose
      - docker-doc
      - podman-docker
    state: absent
  register: docker_remove  
  become: true
  become_method: sudo

- name: "Remove NetExec - We want to use pipx for this"
  package:
    name: 
      - netexec
    state: absent
  become: true
  become_method: sudo

- name: "Remove Containerd/Runc"
  package:
    name: 
      - containerd
      - runc
    state: absent
  when: docker_remove.changed
  become: true
  become_method: sudo

- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - rsyslog
      - ca-certificates
      - curl
      - gh
    state: latest
  become: true
  become_method: sudo

- name: "Add Docker keyring to apt"
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present
  become: true
  become_method: sudo

- name: "Install Docker Repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ distribution }} stable"
    state: present
    update_cache: yes
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: "Install Docker"
  package:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
  become: true
  become_method: sudo
